@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.frostfell.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;