modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/Tamaized/Frostfell/issues"
[[mods]]
modId="frostfell"
version="${version}"
displayName="Frostfell"
credits=""
authors="Tamaized"
description='''
Winter Wonderland Dimension
'''