@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.frostfell.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;