@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.frostfell.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;