@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.frostfell.features;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;